steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: fbbc010cP2007869817
    integrationFlowId: P2007869817-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: fbbc010cP2007869817
    integrationFlowId: P2007869817-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: fbbc010cP2007869817
    integrationFlowId: P2007869817-flow4
    integrationFlowName: P2007869817-flow4
    packageId: CICD
    filePath: P2007869817-flow4.zip